language: python
python:
  - "2.7"
env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - AWS_DEFAULT_REGION=us-west-1
before_install:
    - pip install pytest pytest-cov
install: 
    - pip install -r requirements.txt
script:
    - py.test --cov-report term-missing --cov=. **/*_test.py
